################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
OBJS := 
C_DEPS := 
EXECUTABLES := 

# Every subdirectory with source files must be described here
SUBDIRS := \
tools \
tools/omap \
tools/lib \
tools/lib/libfdt \
tools/gdb \
tools/env \
tools/easylogo \
tools/common \
test \
test/stdint \
test/overlay \
test/env \
test/dm \
scripts/kconfig \
scripts/kconfig/lxdialog \
scripts \
scripts/basic \
post \
post/lib_powerpc \
post/lib_powerpc/fpu \
post/drivers \
post/cpu/ppc4xx \
post/cpu/mpc8xx \
post/cpu/mpc83xx \
post/board/pdm360ng \
post/board/lwmon5 \
net \
lib/zlib \
lib \
lib/tizen \
lib/rsa \
lib/lzo \
lib/lzma \
lib/libfdt \
lib/efi_loader \
lib/efi \
lib/dhry \
lib/bzip2 \
fs/zfs \
fs/yaffs2 \
fs/ubifs \
fs/sandbox \
fs/reiserfs \
fs/jffs2 \
fs \
fs/fat \
fs/ext4 \
fs/cramfs \
fs/cbfs \
examples/standalone \
examples/api \
drivers/watchdog \
drivers/video \
drivers/video/tegra124 \
drivers/video/rockchip \
drivers/video/exynos \
drivers/video/bridge \
drivers/usb/ulpi \
drivers/usb/phy \
drivers/usb/musb-new \
drivers/usb/musb \
drivers/usb/host \
drivers/usb/gadget \
drivers/usb/gadget/udc \
drivers/usb/eth \
drivers/usb/emul \
drivers/usb/dwc3 \
drivers/usb/common \
drivers/twserial \
drivers/tpm \
drivers/timer \
drivers/thermal \
drivers/sysreset \
drivers/spmi \
drivers/spi \
drivers/sound \
drivers/soc/keystone \
drivers/soc \
drivers/serial \
drivers/rtc \
drivers/reset \
drivers/remoteproc \
drivers/ram \
drivers/qe \
drivers/pwm \
drivers/power \
drivers/power/regulator \
drivers/power/pmic \
drivers/power/mfd \
drivers/power/fuel_gauge \
drivers/power/domain \
drivers/power/battery \
drivers/pinctrl/uniphier \
drivers/pinctrl/rockchip \
drivers/pinctrl \
drivers/pinctrl/nxp \
drivers/pinctrl/meson \
drivers/pinctrl/exynos \
drivers/pinctrl/ath79 \
drivers/pcmcia \
drivers/pci \
drivers/pch \
drivers/net \
drivers/net/phy \
drivers/net/ldpaa_eth \
drivers/net/fsl-mc \
drivers/net/fsl-mc/dpio \
drivers/net/fm \
drivers/mtd/ubispl \
drivers/mtd/ubi \
drivers/mtd \
drivers/mtd/spi \
drivers/mtd/onenand \
drivers/mtd/nand \
drivers/mmc \
drivers/misc \
drivers/memory \
drivers/mailbox \
drivers/led \
drivers/input \
drivers/i2c \
drivers/i2c/muxes \
drivers/hwmon \
drivers/gpio \
drivers/fpga \
drivers/dma \
drivers/dfu \
drivers/demo \
drivers/ddr/microchip \
drivers/ddr/marvell/axp \
drivers/ddr/marvell/a38x \
drivers/ddr/fsl \
drivers/ddr/altera \
drivers/crypto/rsa_mod_exp \
drivers/crypto/fsl \
drivers/crypto \
drivers/cpu \
drivers/core \
drivers/clk/uniphier \
drivers/clk/tegra \
drivers/clk/rockchip \
drivers/clk/exynos \
drivers/clk \
drivers/clk/at91 \
drivers \
drivers/bootcount \
drivers/block \
drivers/bios_emulator/x86emu \
drivers/bios_emulator \
drivers/adc \
disk \
common \
common/spl \
common/init \
common/eeprom \
cmd \
board/zyxel/nsa310s \
board/zipitz2 \
board/xilinx/zynqmp \
board/xilinx/zynq/zynq-zybo \
board/xilinx/zynq/zynq-zed \
board/xilinx/zynq/zynq-zc706 \
board/xilinx/zynq/zynq-zc702 \
board/xilinx/zynq/zynq-microzed \
board/xilinx/zynq \
board/xilinx/ppc440-generic \
board/xilinx/ppc405-generic \
board/xilinx/microblaze-generic \
board/xes/xpedite550x \
board/xes/xpedite537x \
board/xes/xpedite520x \
board/xes/xpedite517x \
board/xes/xpedite1000 \
board/xes/common \
board/work-microwave/work_92105 \
board/woodburn \
board/warp7 \
board/warp \
board/wandboard \
board/vscom/baltos \
board/ve8313 \
board/varisys/cyrus \
board/varisys/common \
board/v38b \
board/udoo \
board/tqc/tqma6 \
board/tqc/tqm8xx \
board/tqc/tqm834x \
board/tqc/tqm5200 \
board/tplink/wdr4300 \
board/toradex/colibri_vf \
board/toradex/colibri_t30 \
board/toradex/colibri_t20 \
board/toradex/colibri_pxa270 \
board/toradex/colibri_imx7 \
board/toradex/apalis_t30 \
board/timll/devkit8000 \
board/timll/devkit3250 \
board/ti/ti816x \
board/ti/ti814x \
board/ti/sdp4430 \
board/ti/panda \
board/ti/omap5_uevm \
board/ti/ks2_evm \
board/ti/evm \
board/ti/dra7xx \
board/ti/common \
board/ti/beagle \
board/ti/am57xx \
board/ti/am43xx \
board/ti/am3517crane \
board/ti/am335x \
board/theadorable \
board/terasic/sockit \
board/terasic/de0-nano-soc \
board/teejet/mt_ventoux \
board/technologic/ts4800 \
board/technexion/twister \
board/technexion/tao3530 \
board/technexion/pico-imx6ul \
board/tcm-bf537 \
board/tcm-bf518 \
board/tcl/sl50 \
board/tbs/tbs2910 \
board/t3corp \
board/syteco/zmx25 \
board/sysam/amcore \
board/synopsys/axs10x \
board/sunxi \
board/st/stv0991 \
board/st/stm32f746-disco \
board/st/stm32f429-discovery \
board/sr1500 \
board/spear/x600 \
board/spear/spear600 \
board/spear/spear320 \
board/spear/spear310 \
board/spear/spear300 \
board/spear/common \
board/solidrun/mx6cuboxi \
board/solidrun/clearfog \
board/socrates \
board/silica/pengwyn \
board/siemens/taurus \
board/siemens/smartweb \
board/siemens/rut \
board/siemens/pxm2 \
board/siemens/draco \
board/siemens/corvus \
board/siemens/common \
board/shmin \
board/seco/mx6quq7 \
board/seco/common \
board/schulercontrol/sc_sps_1 \
board/sbc8641d \
board/sbc8548 \
board/sbc8349 \
board/sandisk/sansa_fuze_plus \
board/sandbox \
board/samtec/vining_fpga \
board/samsung/universal_c210 \
board/samsung/trats2 \
board/samsung/trats \
board/samsung/smdkv310/tools \
board/samsung/smdkv310 \
board/samsung/smdkc100 \
board/samsung/smdk5420 \
board/samsung/smdk5250 \
board/samsung/smdk2410 \
board/samsung/origen/tools \
board/samsung/origen \
board/samsung/odroid \
board/samsung/goni \
board/samsung/espresso7420 \
board/samsung/common \
board/samsung/arndale \
board/ronetix/pm9g45 \
board/ronetix/pm9263 \
board/ronetix/pm9261 \
board/rockchip/miniarm_rk3288 \
board/rockchip/kylin_rk3036 \
board/rockchip/fennec_rk3288 \
board/rockchip/evb_rk3399 \
board/rockchip/evb_rk3288 \
board/rockchip/evb_rk3036 \
board/renesas/stout \
board/renesas/silk \
board/renesas/sh7785lcr \
board/renesas/sh7763rdp \
board/renesas/sh7757lcr \
board/renesas/sh7753evb \
board/renesas/sh7752evb \
board/renesas/salvator-x \
board/renesas/rsk7269 \
board/renesas/rsk7264 \
board/renesas/rsk7203 \
board/renesas/rcar-common \
board/renesas/r7780mp \
board/renesas/r2dplus \
board/renesas/r0p7734 \
board/renesas/porter \
board/renesas/lager \
board/renesas/koelsch \
board/renesas/gose \
board/renesas/ecovec \
board/renesas/blanche \
board/renesas/ap325rxa \
board/renesas/alt \
board/renesas/MigoR \
board/raspberrypi/rpi \
board/raidsonic/ib62x0 \
board/radxa/rock2 \
board/quipos/cairo \
board/qualcomm/dragonboard410c \
board/qemu-mips \
board/qca/ap143 \
board/qca/ap121 \
board/pr1 \
board/ppcag/bg0900 \
board/phytec/pcm058 \
board/phytec/pcm052 \
board/phytec/pcm051 \
board/phytec/pcm030 \
board/pdm360ng \
board/pb1x00 \
board/pandora \
board/overo \
board/openrisc/openrisc-generic \
board/omicron/calimain \
board/olimex/mx23_olinuxino \
board/nvidia/whistler \
board/nvidia/venice2 \
board/nvidia/seaboard \
board/nvidia/p2771-0000 \
board/nvidia/p2571 \
board/nvidia/p2371-2180 \
board/nvidia/p2371-0000 \
board/nvidia/nyan-big \
board/nvidia/jetson-tk1 \
board/nvidia/harmony \
board/nvidia/e2220-1170 \
board/nvidia/dalmore \
board/nvidia/cardhu \
board/nokia/rx51 \
board/munices \
board/ms7750se \
board/ms7722se \
board/ms7720se \
board/mpr2 \
board/mpl/vcma9 \
board/mpl/pip405 \
board/mpl/pati \
board/mpl/mip405 \
board/mpl/common \
board/mpc8308_p1m \
board/motionpro \
board/mosaixtech/icon \
board/mini-box/picosam9g45 \
board/micronas/vct \
board/microchip/pic32mzda \
board/maxbcm \
board/logicpd/zoom1 \
board/logicpd/omap3som \
board/logicpd/am3517evm \
board/liebherr/lwmon5 \
board/lg/sniper \
board/lego/ev3 \
board/l+g/vinco \
board/kosagi/novena \
board/kmc/kzm9g \
board/keymile/kmp204x \
board/keymile/km_arm \
board/keymile/km83xx \
board/keymile/km82xx \
board/keymile/common \
board/jupiter \
board/isee/igep00x0 \
board/isee/igep0033 \
board/is1 \
board/ipek01 \
board/ip04 \
board/iomega/iconnect \
board/inversepath/usbarmory \
board/intercontrol/digsy_mtc \
board/intel/minnowmax \
board/intel/galileo \
board/intel/crownbay \
board/intel/cougarcanyon2 \
board/intel/bayleybay \
board/inka4x0 \
board/in-circuit/grasshopper \
board/imx31_phycore \
board/imgtec/malta \
board/ifm/o2dnt2 \
board/ifm/ac14xx \
board/ids/ids8313 \
board/ibf-dsp561 \
board/htkw/mcx \
board/hisilicon/hikey \
board/highbank \
board/h2200 \
board/gumstix/pepper \
board/gumstix/duovero \
board/google/common \
board/google/chromebox_panther \
board/google/chromebook_samus \
board/google/chromebook_link \
board/google/chromebook_jerry \
board/ge/bx50v3 \
board/gdsys/p1022 \
board/gdsys/mpc8308 \
board/gdsys/intip \
board/gdsys/gdppc440etx \
board/gdsys/dlvision \
board/gdsys/common \
board/gdsys/405ex \
board/gdsys/405ep \
board/gateworks/gw_ventana \
board/gaisler/grsim_leon2 \
board/gaisler/grsim \
board/gaisler/gr_xc3s_1500 \
board/gaisler/gr_ep2s60 \
board/gaisler/gr_cpci_ax2000 \
board/freescale/vf610twr \
board/freescale/t4rdb \
board/freescale/t4qds \
board/freescale/t208xrdb \
board/freescale/t208xqds \
board/freescale/t104xrdb \
board/freescale/t1040qds \
board/freescale/t102xrdb \
board/freescale/t102xqds \
board/freescale/s32v234evb \
board/freescale/qemu-ppce500 \
board/freescale/p2041rdb \
board/freescale/p1_twr \
board/freescale/p1_p2_rdb_pc \
board/freescale/p1023rdb \
board/freescale/p1022ds \
board/freescale/p1010rdb \
board/freescale/mx7dsabresd \
board/freescale/mx6ul_14x14_evk \
board/freescale/mx6sxsabresd \
board/freescale/mx6sxsabreauto \
board/freescale/mx6slevk \
board/freescale/mx6sabresd \
board/freescale/mx6qsabreauto \
board/freescale/mx6qarm2 \
board/freescale/mx53smd \
board/freescale/mx53loco \
board/freescale/mx53evk \
board/freescale/mx53ard \
board/freescale/mx51evk \
board/freescale/mx35pdk \
board/freescale/mx31pdk \
board/freescale/mx31ads \
board/freescale/mx28evk \
board/freescale/mx25pdk \
board/freescale/mx23evk \
board/freescale/mpc8641hpcn \
board/freescale/mpc8610hpcd \
board/freescale/mpc8572ds \
board/freescale/mpc8569mds \
board/freescale/mpc8568mds \
board/freescale/mpc8560ads \
board/freescale/mpc8555cds \
board/freescale/mpc8548cds \
board/freescale/mpc8544ds \
board/freescale/mpc8541cds \
board/freescale/mpc8540ads \
board/freescale/mpc8536ds \
board/freescale/mpc837xerdb \
board/freescale/mpc837xemds \
board/freescale/mpc8349itx \
board/freescale/mpc8349emds \
board/freescale/mpc832xemds \
board/freescale/mpc8323erdb \
board/freescale/mpc8315erdb \
board/freescale/mpc8313erdb \
board/freescale/mpc8308rdb \
board/freescale/mpc5121ads \
board/freescale/m548xevb \
board/freescale/m547xevb \
board/freescale/m54455evb \
board/freescale/m54451evb \
board/freescale/m54418twr \
board/freescale/m5373evb \
board/freescale/m5329evb \
board/freescale/m53017evb \
board/freescale/m5282evb \
board/freescale/m5275evb \
board/freescale/m5272c3 \
board/freescale/m5253evbe \
board/freescale/m5253demo \
board/freescale/m5249evb \
board/freescale/m5235evb \
board/freescale/m52277evb \
board/freescale/m5208evbe \
board/freescale/ls2080ardb \
board/freescale/ls2080aqds \
board/freescale/ls2080a \
board/freescale/ls1043ardb \
board/freescale/ls1043aqds \
board/freescale/ls1021atwr \
board/freescale/ls1021aqds \
board/freescale/ls1012ardb \
board/freescale/ls1012aqds \
board/freescale/ls1012afrdm \
board/freescale/corenet_ds \
board/freescale/common \
board/freescale/common/p_corenet \
board/freescale/c29xpcie \
board/freescale/bsc9132qds \
board/freescale/bsc9131rdb \
board/freescale/b4860qds \
board/firefly/firefly-rk3288 \
board/espt \
board/esd/vom405 \
board/esd/vme8349 \
board/esd/pmc440 \
board/esd/pmc405de \
board/esd/plu405 \
board/esd/meesc \
board/esd/mecp5123 \
board/esd/cpci405 \
board/esd/cpci2dp \
board/esd/common/xilinx_jtag \
board/esd/common \
board/emulation/qemu-x86 \
board/embest/mx6boards \
board/el/el6x \
board/egnite/ethernut5 \
board/efi/efi-x86 \
board/ebv/socrates \
board/dnp5370 \
board/dfi/dfi-bt700 \
board/denx/mcvevk \
board/denx/ma5d4evk \
board/denx/m53evk \
board/denx/m28evk \
board/dbau1x00 \
board/davinci/ea20 \
board/davinci/da8xxevm \
board/davedenx/aria \
board/d-link/dns325 \
board/creative/xfi3 \
board/corscience/tricorder \
board/coreboot/coreboot \
board/congatec/conga-qeval20-qa3-e3845 \
board/congatec/cgtqmx6eval \
board/compulab/trimslice \
board/compulab/common \
board/compulab/cm_t54 \
board/compulab/cm_t43 \
board/compulab/cm_t3517 \
board/compulab/cm_t35 \
board/compulab/cm_t335 \
board/compulab/cm_fx6 \
board/compal/paz00 \
board/cobra5272 \
board/cm5200 \
board/cm-bf561 \
board/cm-bf548 \
board/cm-bf537u \
board/cm-bf537e \
board/cm-bf533 \
board/cm-bf527 \
board/cloudengines/pogo_e02 \
board/cirrus/edb93xx \
board/chipspark/popmetal_rk3288 \
board/cei/cei-tk1-som \
board/ccv/xpress \
board/cavium/thunderx \
board/canmb \
board/calao/usb_a9263 \
board/cadence/xtfpga \
board/buffalo/lsxl \
board/broadcom/bcm_ep \
board/broadcom/bcm28155_ap \
board/broadcom/bcm23550_w1d \
board/br4 \
board/boundary/nitrogen6x \
board/bosch/shc \
board/bluewater/snapper9260 \
board/bluewater/gurnard \
board/bluegiga/apx4devkit \
board/blackvme \
board/blackstamp \
board/birdland/bav335x \
board/bf609-ezkit \
board/bf561-ezkit \
board/bf561-acvilon \
board/bf548-ezkit \
board/bf538f-ezkit \
board/bf537-stamp \
board/bf537-srv1 \
board/bf537-pnav \
board/bf537-minotaur \
board/bf533-stamp \
board/bf533-ezkit \
board/bf527-sdp \
board/bf527-ezkit \
board/bf527-ad7160-eval \
board/bf526-ezbrd \
board/bf525-ucr2 \
board/bf518f-ezbrd \
board/bf506f-ezkit \
board/bct-brettl2 \
board/barco/titanium \
board/barco/platinum \
board/bachmann/ot1200 \
board/avionic-design/common \
board/atmel/sama5d4ek \
board/atmel/sama5d4_xplained \
board/atmel/sama5d3xek \
board/atmel/sama5d3_xplained \
board/atmel/sama5d2_xplained \
board/atmel/sama5d2_ptc \
board/atmel/atstk1000 \
board/atmel/atngw100mkii \
board/atmel/atngw100 \
board/atmel/at91sam9x5ek \
board/atmel/at91sam9rlek \
board/atmel/at91sam9n12ek \
board/atmel/at91sam9m10g45ek \
board/atmel/at91sam9263ek \
board/atmel/at91sam9261ek \
board/atmel/at91sam9260ek \
board/atmel/at91rm9200ek \
board/atmark-techno/armadillo-800eva \
board/astro/mcf5373l \
board/armltd/vexpress64 \
board/armltd/vexpress \
board/armltd/integrator \
board/armadeus/apf27 \
board/aristainetos \
board/amlogic/odroid-c2 \
board/amcc/yucca \
board/amcc/yosemite \
board/amcc/walnut \
board/amcc/sequoia \
board/amcc/redwood \
board/amcc/makalu \
board/amcc/luan \
board/amcc/kilauea \
board/amcc/katmai \
board/amcc/common \
board/amcc/canyonlands \
board/amcc/bubinga \
board/amcc/bamboo \
board/amcc/acadia \
board/amazon/kc1 \
board/altera/cyclone5-socdk \
board/altera/arria5-socdk \
board/alphaproject/ap_sh4a_4a \
board/advantech/som-db5800-som-6867 \
board/advantech/dms-ba16 \
board/abilis/tb100 \
board/a4m072 \
board/a3m071 \
board/Synology/ds414 \
board/Seagate/nas220 \
board/Seagate/goflexhome \
board/Seagate/dockstar \
board/Marvell/sheevaplug \
board/Marvell/openrd \
board/Marvell/guruplug \
board/Marvell/gplugd \
board/Marvell/dreamplug \
board/Marvell/db-mv784mp-gp \
board/Marvell/db-88f6820-gp \
board/Marvell/db-88f6720 \
board/Marvell/aspenite \
board/LaCie/netspace_v2 \
board/LaCie/net2big_v2 \
board/LaCie/edminiv2 \
board/LaCie/common \
board/CarMediaLab/flea3 \
board/BuS/eb_cpu5282 \
board/BuR/common \
board/BuR/brxre1 \
board/BuR/brppt1 \
board/Barix/ipam390 \
board/Arcturus/ucp1020 \
board/AndesTech/adp-ag101p \
board/8dtech/eco5pk \
arch/xtensa/lib \
arch/xtensa/cpu \
arch/x86/lib \
arch/x86/lib/fsp \
arch/x86/lib/efi \
arch/x86/cpu \
arch/x86/cpu/queensbay \
arch/x86/cpu/quark \
arch/x86/cpu/qemu \
arch/x86/cpu/ivybridge \
arch/x86/cpu/intel_common \
arch/x86/cpu/efi \
arch/x86/cpu/coreboot \
arch/x86/cpu/broadwell \
arch/x86/cpu/baytrail \
arch/sparc/lib \
arch/sparc/cpu/leon3 \
arch/sparc/cpu/leon2 \
arch/sh/lib \
arch/sh/cpu/sh4 \
arch/sh/cpu/sh3 \
arch/sh/cpu/sh2 \
arch/sandbox/lib \
arch/sandbox/cpu \
arch/powerpc/lib \
arch/powerpc/cpu/ppc4xx \
arch/powerpc/cpu/mpc8xxx \
arch/powerpc/cpu/mpc8xx \
arch/powerpc/cpu/mpc86xx \
arch/powerpc/cpu/mpc85xx \
arch/powerpc/cpu/mpc83xx \
arch/powerpc/cpu/mpc8260 \
arch/powerpc/cpu/mpc5xxx \
arch/powerpc/cpu/mpc5xx \
arch/powerpc/cpu/mpc512x \
arch/openrisc/lib \
arch/openrisc/cpu \
arch/nios2/lib \
arch/nios2/cpu \
arch/nds32/lib \
arch/nds32/cpu/n1213 \
arch/nds32/cpu/n1213/ag101 \
arch/mips/mach-pic32 \
arch/mips/mach-au1x00 \
arch/mips/mach-ath79 \
arch/mips/mach-ath79/qca953x \
arch/mips/mach-ath79/ar934x \
arch/mips/mach-ath79/ar933x \
arch/mips/lib \
arch/mips/cpu \
arch/microblaze/lib \
arch/microblaze/cpu \
arch/m68k/lib \
arch/m68k/cpu/mcf547x_8x \
arch/m68k/cpu/mcf5445x \
arch/m68k/cpu/mcf532x \
arch/m68k/cpu/mcf530x \
arch/m68k/cpu/mcf52x2 \
arch/m68k/cpu/mcf523x \
arch/m68k/cpu/mcf5227x \
arch/blackfin/lib \
arch/blackfin/cpu \
arch/avr32/lib \
arch/avr32/cpu \
arch/avr32/cpu/at32ap700x \
arch/arm/mach-zynq \
arch/arm/mach-versatile \
arch/arm/mach-uniphier \
arch/arm/mach-uniphier/sbc \
arch/arm/mach-uniphier/pll \
arch/arm/mach-uniphier/pinctrl \
arch/arm/mach-uniphier/memconf \
arch/arm/mach-uniphier/init \
arch/arm/mach-uniphier/early-pinctrl \
arch/arm/mach-uniphier/early-clk \
arch/arm/mach-uniphier/dram \
arch/arm/mach-uniphier/debug-uart \
arch/arm/mach-uniphier/clk \
arch/arm/mach-uniphier/boot-mode \
arch/arm/mach-uniphier/bcu \
arch/arm/mach-uniphier/arm64 \
arch/arm/mach-uniphier/arm32 \
arch/arm/mach-tegra \
arch/arm/mach-tegra/tegra30 \
arch/arm/mach-tegra/tegra210 \
arch/arm/mach-tegra/tegra20 \
arch/arm/mach-tegra/tegra186 \
arch/arm/mach-tegra/tegra124 \
arch/arm/mach-tegra/tegra114 \
arch/arm/mach-sunxi \
arch/arm/mach-stm32/stm32f7 \
arch/arm/mach-stm32/stm32f4 \
arch/arm/mach-stm32/stm32f1 \
arch/arm/mach-socfpga \
arch/arm/mach-snapdragon \
arch/arm/mach-s5pc1xx \
arch/arm/mach-rockchip \
arch/arm/mach-rockchip/rk3399 \
arch/arm/mach-rockchip/rk3288 \
arch/arm/mach-rockchip/rk3036 \
arch/arm/mach-rmobile \
arch/arm/mach-orion5x \
arch/arm/mach-mvebu \
arch/arm/mach-mvebu/serdes/axp \
arch/arm/mach-mvebu/serdes/a38x \
arch/arm/mach-meson \
arch/arm/mach-kirkwood \
arch/arm/mach-keystone \
arch/arm/mach-highbank \
arch/arm/mach-exynos \
arch/arm/mach-davinci \
arch/arm/mach-bcm283x \
arch/arm/mach-at91 \
arch/arm/mach-at91/armv7 \
arch/arm/mach-at91/arm926ejs \
arch/arm/mach-at91/arm920t \
arch/arm/lib \
arch/arm/include/debug \
arch/arm/include/asm/arch-mx35 \
arch/arm/imx-common \
arch/arm/cpu/sa1100 \
arch/arm/cpu/pxa \
arch/arm/cpu \
arch/arm/cpu/armv8/zynqmp \
arch/arm/cpu/armv8 \
arch/arm/cpu/armv8/s32v234 \
arch/arm/cpu/armv8/hisilicon \
arch/arm/cpu/armv8/fsl-layerscape \
arch/arm/cpu/armv7m \
arch/arm/cpu/armv7 \
arch/arm/cpu/armv7/vf610 \
arch/arm/cpu/armv7/sunxi \
arch/arm/cpu/armv7/stv0991 \
arch/arm/cpu/armv7/s5p-common \
arch/arm/cpu/armv7/omap5 \
arch/arm/cpu/armv7/omap4 \
arch/arm/cpu/armv7/omap3 \
arch/arm/cpu/armv7/omap-common \
arch/arm/cpu/armv7/mx7 \
arch/arm/cpu/armv7/mx6 \
arch/arm/cpu/armv7/mx5 \
arch/arm/cpu/armv7/ls102xa \
arch/arm/cpu/armv7/kona-common \
arch/arm/cpu/armv7/iproc-common \
arch/arm/cpu/armv7/bcmnsp \
arch/arm/cpu/armv7/bcmcygnus \
arch/arm/cpu/armv7/bcm281xx \
arch/arm/cpu/armv7/bcm235xx \
arch/arm/cpu/armv7/am33xx \
arch/arm/cpu/arm946es \
arch/arm/cpu/arm926ejs \
arch/arm/cpu/arm926ejs/spear \
arch/arm/cpu/arm926ejs/omap \
arch/arm/cpu/arm926ejs/mxs \
arch/arm/cpu/arm926ejs/mx27 \
arch/arm/cpu/arm926ejs/mx25 \
arch/arm/cpu/arm926ejs/lpc32xx \
arch/arm/cpu/arm926ejs/armada100 \
arch/arm/cpu/arm920t \
arch/arm/cpu/arm920t/s3c24x0 \
arch/arm/cpu/arm920t/imx \
arch/arm/cpu/arm920t/ep93xx \
arch/arm/cpu/arm720t \
arch/arm/cpu/arm1176 \
arch/arm/cpu/arm1136 \
arch/arm/cpu/arm1136/mx35 \
arch/arm/cpu/arm1136/mx31 \
arch/arm/cpu/arm11 \
arch/arc/lib \
arch/arc/cpu/arcv2 \
arch/arc/cpu/arcv1 \
api \

