################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
O_SRCS += \
../cmd/bdinfo.o \
../cmd/boot.o \
../cmd/bootm.o \
../cmd/built-in.o \
../cmd/cache.o \
../cmd/console.o \
../cmd/date.o \
../cmd/disk.o \
../cmd/echo.o \
../cmd/elf.o \
../cmd/exit.o \
../cmd/ext2.o \
../cmd/fat.o \
../cmd/flash.o \
../cmd/help.o \
../cmd/itest.o \
../cmd/load.o \
../cmd/mem.o \
../cmd/misc.o \
../cmd/mtdparts.o \
../cmd/nand.o \
../cmd/net.o \
../cmd/nvedit.o \
../cmd/pcmcia.o \
../cmd/reginfo.o \
../cmd/source.o \
../cmd/test.o \
../cmd/ubi.o \
../cmd/ubifs.o \
../cmd/usb.o \
../cmd/version.o \
../cmd/ximg.o \
../cmd/yaffs2.o 

C_SRCS += \
../cmd/aes.c \
../cmd/ambapp.c \
../cmd/armflash.c \
../cmd/bdinfo.c \
../cmd/bedbug.c \
../cmd/blkcache.c \
../cmd/blob.c \
../cmd/bmp.c \
../cmd/boot.c \
../cmd/bootefi.c \
../cmd/booti.c \
../cmd/bootldr.c \
../cmd/bootm.c \
../cmd/bootmenu.c \
../cmd/bootstage.c \
../cmd/bootz.c \
../cmd/cache.c \
../cmd/cbfs.c \
../cmd/clk.c \
../cmd/console.c \
../cmd/cplbinfo.c \
../cmd/cpu.c \
../cmd/cramfs.c \
../cmd/dataflash_mmc_mux.c \
../cmd/date.c \
../cmd/dcr.c \
../cmd/demo.c \
../cmd/dfu.c \
../cmd/diag.c \
../cmd/disk.c \
../cmd/display.c \
../cmd/dtt.c \
../cmd/echo.c \
../cmd/eeprom.c \
../cmd/efi.c \
../cmd/elf.c \
../cmd/ethsw.c \
../cmd/exit.c \
../cmd/ext2.c \
../cmd/ext4.c \
../cmd/fastboot.c \
../cmd/fat.c \
../cmd/fdc.c \
../cmd/fdt.c \
../cmd/fitupd.c \
../cmd/flash.c \
../cmd/fpga.c \
../cmd/fpgad.c \
../cmd/fs.c \
../cmd/fs_uuid.c \
../cmd/fuse.c \
../cmd/gettime.c \
../cmd/gpio.c \
../cmd/gpt.c \
../cmd/hash.c \
../cmd/help.c \
../cmd/host.c \
../cmd/i2c.c \
../cmd/ide.c \
../cmd/immap.c \
../cmd/ini.c \
../cmd/io.c \
../cmd/iotrace.c \
../cmd/irq.c \
../cmd/itest.c \
../cmd/jffs2.c \
../cmd/ldrinfo.c \
../cmd/led.c \
../cmd/license.c \
../cmd/load.c \
../cmd/log.c \
../cmd/lzmadec.c \
../cmd/mac.c \
../cmd/md5sum.c \
../cmd/mdio.c \
../cmd/mem.c \
../cmd/mfsl.c \
../cmd/mii.c \
../cmd/misc.c \
../cmd/mmc.c \
../cmd/mmc_spi.c \
../cmd/mp.c \
../cmd/mtdparts.c \
../cmd/nand.c \
../cmd/net.c \
../cmd/nvedit.c \
../cmd/onenand.c \
../cmd/otp.c \
../cmd/part.c \
../cmd/pci.c \
../cmd/pcmcia.c \
../cmd/pmic.c \
../cmd/portio.c \
../cmd/pxe.c \
../cmd/qfw.c \
../cmd/read.c \
../cmd/reginfo.c \
../cmd/regulator.c \
../cmd/reiser.c \
../cmd/remoteproc.c \
../cmd/sata.c \
../cmd/scsi.c \
../cmd/setexpr.c \
../cmd/sf.c \
../cmd/sha1sum.c \
../cmd/softswitch.c \
../cmd/sound.c \
../cmd/source.c \
../cmd/spi.c \
../cmd/spibootldr.c \
../cmd/spl.c \
../cmd/strings.c \
../cmd/terminal.c \
../cmd/test.c \
../cmd/thordown.c \
../cmd/time.c \
../cmd/tpm.c \
../cmd/tpm_test.c \
../cmd/trace.c \
../cmd/tsi148.c \
../cmd/ubi.c \
../cmd/ubifs.c \
../cmd/universe.c \
../cmd/unzip.c \
../cmd/usb.c \
../cmd/usb_mass_storage.c \
../cmd/version.c \
../cmd/ximg.c \
../cmd/yaffs2.c \
../cmd/zfs.c \
../cmd/zip.c 

OBJS += \
./cmd/aes.o \
./cmd/ambapp.o \
./cmd/armflash.o \
./cmd/bdinfo.o \
./cmd/bedbug.o \
./cmd/blkcache.o \
./cmd/blob.o \
./cmd/bmp.o \
./cmd/boot.o \
./cmd/bootefi.o \
./cmd/booti.o \
./cmd/bootldr.o \
./cmd/bootm.o \
./cmd/bootmenu.o \
./cmd/bootstage.o \
./cmd/bootz.o \
./cmd/cache.o \
./cmd/cbfs.o \
./cmd/clk.o \
./cmd/console.o \
./cmd/cplbinfo.o \
./cmd/cpu.o \
./cmd/cramfs.o \
./cmd/dataflash_mmc_mux.o \
./cmd/date.o \
./cmd/dcr.o \
./cmd/demo.o \
./cmd/dfu.o \
./cmd/diag.o \
./cmd/disk.o \
./cmd/display.o \
./cmd/dtt.o \
./cmd/echo.o \
./cmd/eeprom.o \
./cmd/efi.o \
./cmd/elf.o \
./cmd/ethsw.o \
./cmd/exit.o \
./cmd/ext2.o \
./cmd/ext4.o \
./cmd/fastboot.o \
./cmd/fat.o \
./cmd/fdc.o \
./cmd/fdt.o \
./cmd/fitupd.o \
./cmd/flash.o \
./cmd/fpga.o \
./cmd/fpgad.o \
./cmd/fs.o \
./cmd/fs_uuid.o \
./cmd/fuse.o \
./cmd/gettime.o \
./cmd/gpio.o \
./cmd/gpt.o \
./cmd/hash.o \
./cmd/help.o \
./cmd/host.o \
./cmd/i2c.o \
./cmd/ide.o \
./cmd/immap.o \
./cmd/ini.o \
./cmd/io.o \
./cmd/iotrace.o \
./cmd/irq.o \
./cmd/itest.o \
./cmd/jffs2.o \
./cmd/ldrinfo.o \
./cmd/led.o \
./cmd/license.o \
./cmd/load.o \
./cmd/log.o \
./cmd/lzmadec.o \
./cmd/mac.o \
./cmd/md5sum.o \
./cmd/mdio.o \
./cmd/mem.o \
./cmd/mfsl.o \
./cmd/mii.o \
./cmd/misc.o \
./cmd/mmc.o \
./cmd/mmc_spi.o \
./cmd/mp.o \
./cmd/mtdparts.o \
./cmd/nand.o \
./cmd/net.o \
./cmd/nvedit.o \
./cmd/onenand.o \
./cmd/otp.o \
./cmd/part.o \
./cmd/pci.o \
./cmd/pcmcia.o \
./cmd/pmic.o \
./cmd/portio.o \
./cmd/pxe.o \
./cmd/qfw.o \
./cmd/read.o \
./cmd/reginfo.o \
./cmd/regulator.o \
./cmd/reiser.o \
./cmd/remoteproc.o \
./cmd/sata.o \
./cmd/scsi.o \
./cmd/setexpr.o \
./cmd/sf.o \
./cmd/sha1sum.o \
./cmd/softswitch.o \
./cmd/sound.o \
./cmd/source.o \
./cmd/spi.o \
./cmd/spibootldr.o \
./cmd/spl.o \
./cmd/strings.o \
./cmd/terminal.o \
./cmd/test.o \
./cmd/thordown.o \
./cmd/time.o \
./cmd/tpm.o \
./cmd/tpm_test.o \
./cmd/trace.o \
./cmd/tsi148.o \
./cmd/ubi.o \
./cmd/ubifs.o \
./cmd/universe.o \
./cmd/unzip.o \
./cmd/usb.o \
./cmd/usb_mass_storage.o \
./cmd/version.o \
./cmd/ximg.o \
./cmd/yaffs2.o \
./cmd/zfs.o \
./cmd/zip.o 

C_DEPS += \
./cmd/aes.d \
./cmd/ambapp.d \
./cmd/armflash.d \
./cmd/bdinfo.d \
./cmd/bedbug.d \
./cmd/blkcache.d \
./cmd/blob.d \
./cmd/bmp.d \
./cmd/boot.d \
./cmd/bootefi.d \
./cmd/booti.d \
./cmd/bootldr.d \
./cmd/bootm.d \
./cmd/bootmenu.d \
./cmd/bootstage.d \
./cmd/bootz.d \
./cmd/cache.d \
./cmd/cbfs.d \
./cmd/clk.d \
./cmd/console.d \
./cmd/cplbinfo.d \
./cmd/cpu.d \
./cmd/cramfs.d \
./cmd/dataflash_mmc_mux.d \
./cmd/date.d \
./cmd/dcr.d \
./cmd/demo.d \
./cmd/dfu.d \
./cmd/diag.d \
./cmd/disk.d \
./cmd/display.d \
./cmd/dtt.d \
./cmd/echo.d \
./cmd/eeprom.d \
./cmd/efi.d \
./cmd/elf.d \
./cmd/ethsw.d \
./cmd/exit.d \
./cmd/ext2.d \
./cmd/ext4.d \
./cmd/fastboot.d \
./cmd/fat.d \
./cmd/fdc.d \
./cmd/fdt.d \
./cmd/fitupd.d \
./cmd/flash.d \
./cmd/fpga.d \
./cmd/fpgad.d \
./cmd/fs.d \
./cmd/fs_uuid.d \
./cmd/fuse.d \
./cmd/gettime.d \
./cmd/gpio.d \
./cmd/gpt.d \
./cmd/hash.d \
./cmd/help.d \
./cmd/host.d \
./cmd/i2c.d \
./cmd/ide.d \
./cmd/immap.d \
./cmd/ini.d \
./cmd/io.d \
./cmd/iotrace.d \
./cmd/irq.d \
./cmd/itest.d \
./cmd/jffs2.d \
./cmd/ldrinfo.d \
./cmd/led.d \
./cmd/license.d \
./cmd/load.d \
./cmd/log.d \
./cmd/lzmadec.d \
./cmd/mac.d \
./cmd/md5sum.d \
./cmd/mdio.d \
./cmd/mem.d \
./cmd/mfsl.d \
./cmd/mii.d \
./cmd/misc.d \
./cmd/mmc.d \
./cmd/mmc_spi.d \
./cmd/mp.d \
./cmd/mtdparts.d \
./cmd/nand.d \
./cmd/net.d \
./cmd/nvedit.d \
./cmd/onenand.d \
./cmd/otp.d \
./cmd/part.d \
./cmd/pci.d \
./cmd/pcmcia.d \
./cmd/pmic.d \
./cmd/portio.d \
./cmd/pxe.d \
./cmd/qfw.d \
./cmd/read.d \
./cmd/reginfo.d \
./cmd/regulator.d \
./cmd/reiser.d \
./cmd/remoteproc.d \
./cmd/sata.d \
./cmd/scsi.d \
./cmd/setexpr.d \
./cmd/sf.d \
./cmd/sha1sum.d \
./cmd/softswitch.d \
./cmd/sound.d \
./cmd/source.d \
./cmd/spi.d \
./cmd/spibootldr.d \
./cmd/spl.d \
./cmd/strings.d \
./cmd/terminal.d \
./cmd/test.d \
./cmd/thordown.d \
./cmd/time.d \
./cmd/tpm.d \
./cmd/tpm_test.d \
./cmd/trace.d \
./cmd/tsi148.d \
./cmd/ubi.d \
./cmd/ubifs.d \
./cmd/universe.d \
./cmd/unzip.d \
./cmd/usb.d \
./cmd/usb_mass_storage.d \
./cmd/version.d \
./cmd/ximg.d \
./cmd/yaffs2.d \
./cmd/zfs.d \
./cmd/zip.d 


# Each subdirectory must supply rules for building sources it contributes
cmd/%.o: ../cmd/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross GCC Compiler'
	arm-linux-gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


